app:
  log_level:nobugs
client_urls:
  binance:
    dex:dex.binance.org
    explorer:explorer.binance.org
assets_manager_api:assets.trustwallet.com/api
urls:
  assets_app:assetscdn.trustwallet.com
  logo:trustwallet.com/assets/images/favicon.png
time_format:2026-01-02
validators_settings:root_folder:allowedfiles:github@blockchains.dapps
media
